### ISSUE TITLE
Feature request: Replaced input

### ISSUE THREAD

**Issue by dobrowolsk** [NiHoel/Anno1800Calculator#13]
There are items which replace an input material for a production building with another one.

Example 1: Goldsmith Gilbert:
Applies to: Jewelry Workshop
Input: Gold
New Input: Gold Ore

Example 1: Torcedor Lucia:
Applies to: Cigars Workshop
Input: Inlay
New Input: Timber

I'd love to be able to enable input replacement for a building type, as I never set up Jewelry Workshops and Cigar Workshops without these items.

See a list of input replacement options here: https://www.annothek.net/wbb5/forum/index.php?thread/10742-liste-aller-items-die-denn-input-ver%C3%A4ndern/

**Comment by NiHoel** [comment]
closed by 2fedd2a8305be97dc8feca88ffb1f7cf58d3af75

**Comment by byWulf** [comment]
Good day @NiHoel ,

did something change since 2019? I am missing Torcedor Lucia, and can't find her in the item equipment dialog. Is this a bug or intended? :) Really need the feature to see, how much timber buildings I need.

If it's a bug, I would gladly search for it and open a PR 👍 Thanks in advance for your response.

**Comment by NiHoel** [comment]
It's there: 
![image](https://user-images.githubusercontent.com/28017252/112647922-48332400-8e49-11eb-87c9-c96d526574a2.png)

Did you check "Extra Goods" in the settings?

**Comment by byWulf** [comment]
Thanks a lot, that was the option I was looking for! :)
