### ISSUE TITLE
Slaughterhouse rounding issue

### ISSUE THREAD

**Issue by britiscurious** [NiHoel/Anno1800Calculator#15]
Enable "Show number of buildings with decimals"
Set number of Workers to 1000

Required Number of Buildings for Slaughterhouse is shown as 1.00

Enable "Show number of buildings with decimals"

Required Number of Buildings for Slaughterhouse is shown as 2

I usually use the rounded values.
This rounding issue leads to the weird situation that (with "Show number of buildings with decimals" disabled) a need of

2 Slaughterhouses
1 Soap Factory
2 Pig Farms

is shown.

But the 2 Pig Farms are not sufficient to produce enough goods for the 2 Slaughterhouses + 1 Soap Factory.

Either the correct rounding for 1.00 Slaughterhouse is 1 or the required "rounded amount" of Pig Farms should be "rounded amount" of Slaughterhouses" + "rounded amount" of Soap Factories

**Comment by NiHoel** [comment]
I agree that 1.00 rounds to 2 is a bit confusing. The reason is that internally the value 1.000002 is used. In the first case trailing decimals are truncat while in the second case it is rounded up to the next integer.

The value for the pig farms is ok, since it tells you how many you need to supply your population, and NOT how many you need to run the succeeding production buildings at 100%.
