### ISSUE TITLE
Feature Request\Contribution - Highlight Updated Tiles

### ISSUE THREAD

**Issue by amitdey1987** [NiHoel/Anno1800Calculator#19]
It would be great if we could highlight the tiles that are updated when we enter a new input.
If you are open to contributions, I would like to work on this.

**Comment by NiHoel** [comment]
In my opinion the option "Highlight missing buildings" is sufficient. I interpret your approach that the tiles are highlighted for a short time (and not input of the currently built buildings is required). But for larger cities a lot of tiles will highlight which is no benefit to the user.

**Comment by amitdey1987** [comment]
i was not aware of this feature. looks great. But in my opinion, it is a little cumbersome to manually update each existing building.
Another option would be have an additional "base/existing" count for all population tier.
And a checkbox named "only show diff buildings"
This was the app can generate the list of buildings for old and new users, and if the checkbox is selected, then only show the newly required building.

I feel this feature will be very helpful for mobile users, since all tiles take too much space.

**Comment by NiHoel** [comment]
Feel free to implement the feature "only show diff buildings" and create a pull request afterwards.

I am not sure what you mean by "base/existing" count for all population tier: Does this counter refer to the number of buildings or number of citizens?

**Comment by amitdey1987** [comment]
as an example.
consider these inputs
existing-
farmers:480 workers:0 ...
desired
farmers:960 workers:0 ...

logic:
now assume that 480 workers require 1 fishery, 1 cotton farm, 1 workers clothes.
and
also assume that 960 workers require 1 fishery, 2 cotton farm, 2 worker clothes.

when the "only show duff building" is selected, we will only show the necessary buildings
1 new cotton farm. (total 2)
1 new worker clothes. (total 2)

The idea is i am taking a logical step from upgrading from 480 workers to 960 workers. I would like to know the additional buildings I need to support my population.

Does this seem useful to you ?

**Comment by NiHoel** [comment]
This seems to be a valuable feature if the following conditions are met:

- Proper integration with the option "Show number of buildings with decimals" (use rounded up values in this case)
- Proper integration with the option "Highlight missing buildings"
- Nice GUI integration to copy the number from "desired" citizens to "existing"
- An option to enable the feature

Care: A lot of code re-write will be required since the current design is that there is a single amount value and changes are propagated to other classes (Needs, Products, ...). It is non-trivial to install a second layer for population count.
