### ISSUE TITLE
[Feature Request] rename Islands | address Buildings individually

### ISSUE THREAD

**Issue by Xello99** [NiHoel/Anno1800Calculator#62]
Hello,
first I wanna thank you for making this calculator, it's really fun to use it alongside Anno.

Now, to my feature requests (let me know if you want me to open two seperate issues for the two requests):

Rename Islands: this is relatively short; I'm playing a coop session with a friend who likes to rename our Islands all the time. It's quite an inconvenience for me though, as I always have to delete the "old" island in the calculator, and add the "new" one. So if there is any way to rename existing islands, that would be great.

Address buildings individually: What I mean is, let's say I have 8 Sewing machine factories, but only four off them are in range off the trade union and thus have different productivities and Dario and Bruno who produce goods on the side. It would be great if I could address each building individually, and set the percentage and items for each one. 
Currently I solve the productivity thing by just calculating the average produvctivity which works fine, but for the items it's not so easy. 
Maybe, if addressing each individual building would clutter the calculator to much, you could add a counter, where one could specifiy how many of the buildings are in range of the trade union.

The last one actually became really prevelant in the arctic, as the limited space forced me to build some buildings in range of the trade union, while others just didn't fit inside anymore.

Have a nice day :)

**Comment by NiHoel** [comment]
**Rename Islands**: I'll probably implement this. Then, you will see it first in the preview version: https://nihoel.github.io/Anno1800Calculator-preview/

**Address buildings individually**: That is out of scope for my calculator. If you want to have fine-grained control of one factory type being affected by different trade unions, have a look at this calculator: http://www.manueltransfeld.de/public/projects/plan1800/preview/
(note: this is still a preview version since land of lions dlc and palace dlc are not yet implemented in the release version; the author does not seem to have time to complete the update at the moment)
An alternative is to work with multiple (artificial) islands to model out-of-range factories and import the goods from there.

**Comment by NiHoel** [comment]
Rename Islands: I pushed an update for the preview.
