### ISSUE TITLE
Workforce Overview

### ISSUE THREAD

**Issue by c9w2** [NiHoel/Anno1800Calculator#79]
Hi, would there be a way to implement a workforce overview showing you how much workforce is used in which building?
E.g.: Farmers 45 in fisheries, 200 in distillery etc.
Lots of times workforce calculation is (way) off and I can't always find, where the calculator made a mistake.
As one can see in the screenshot, everything is built correctly. When checking in-game, I used 2995 engineers whereas the calculator says, I need 1000 more and I don't know why. Thanks in advance!
![Workforce](https://user-images.githubusercontent.com/103927705/163782544-f4cb3e55-919f-47a1-a18f-51d82a314015.png)

**Comment by NiHoel** [comment]
Computing the required workforce has never been the primary focus of this calculator. Therefore, the calculation and configuration options are rather rudimentary compared to goods calculation.
Besides, I doubt how an overview could improve fine-tuning the calculator since the game does not offer such an overview either to compare to.

Did you ensure that the following aspects are correctly represented in your calculation?
* Island workforce
* Items changing the workforce type (see help for equipping items)
* Items reducing the amount of workforce (percentage input field in the factory configuration dialogue)

**Comment by c9w2** [comment]
Pity, I alwayse use(d) the calculator to optimize my population. I checked everything (multiple times) and the calculator seems to count the workforce from the motor assembly line twice. But that only solves part of the problem. So maybe there is just something wrong in the calculation. The error appeared first after the last update coming with the hacienda and the ability to replace the type of workforce needed.
An overview could be cross-checked with the production stats in-game, but as you said, the information ist there, just scattered.

**Comment by NiHoel** [comment]
![grafik](https://user-images.githubusercontent.com/28017252/165077876-2799b60d-1e5b-46e7-981d-a0b9d4642a1f.png)
There is definitely something wrong here. Good that you noticed it. However, you might need to wait until the weekend until I can inspect the cause.

Can you send me the configuration file of the calculator and a screenshot of the used workforce so that I can check how it is supposed to be?

**Comment by c9w2** [comment]
Screenshot from the game or the calculator?

**Comment by NiHoel** [comment]
Can you please check whether the issue still occurs in this version: https://nihoel.github.io/Anno1800Calculator-preview/

**Comment by c9w2** [comment]
Engineers are fine now (thx for looking into it so fast!), but the calculator still asks for 20 Jornalero workforce and I don't know why.

**Comment by NiHoel** [comment]
Can you go to download -> export configuration and send it to me? Then, I can inspect it and tell you the reason.
