### ISSUE TITLE
[Question] How is "All Islands" tab stats calculated ?

### ISSUE THREAD

**Issue by JerjerBinks** [NiHoel/Anno1800Calculator#91]
Hi,

Sorry to open an issue just to ask a question, if there is another way please tell me.

I'm wondering if the All Islands tab stats are computed thanks to each individual island stat ?
Because if it is, it doesn't seem to work for me.
When I change the number of homes or the number of factories on a single island, it doesn't change on the All Island tab.
Any reason ?
I thought the All Island tab was a way to check if "globally" you have enough buildings to satisfy the needs or if you have too many and so that you could instead transfer goods to optimize your management !

Thank you for all the work you have done on this calculator, it is really impressive and still running !

**Comment by NiHoel** [comment]
No, the "All Islands" is a special kind of island (e.g. all tiers are displayed) but does not aggregate the data from other islands.

**Comment by JerjerBinks** [comment]
Ok thank you for your answer!
Why not making an aggregation considering that all the data are available
to do so?
I'm not saying that it would be extremely useful 😉

**Comment by NiHoel** [comment]
Because an aggregated view is a lot of effort to implement:
I cannot use the existing UI: all input fields would have to be disabled and equipment of items (some islands have others not) cannot be displayed in the current UI
A new UI specifically for aggregation is a huge effort: Front-end design, data aggregation, implementation, bug fixing, and testing. 

Currently, I'm not even sure whether I manage to implement all changes for DLC12 until release.

**Comment by JerjerBinks** [comment]
Wow ok I didn't think of so much intrication!
Thanks again and good luck for the next DLC!

For information and if it can be useful, there is an app on Android : Anno
1800 Companion Tool.
There are some useful things even if less complex : expeditions materials,
old nate shop, museum and garden collections.
